/* Generated by tools/bake_fonts.py. Do not edit. */
#ifndef WEDGE_FONTS_H
#define WEDGE_FONTS_H

#include "wedge/font.h"

extern const wg_font_t wg_font_clock;
extern const wg_font_t wg_font_clock_s;
extern const wg_font_t wg_font_date;
extern const wg_font_t wg_font_kicker;
extern const wg_font_t wg_font_label;
extern const wg_font_t wg_font_quote;
extern const wg_font_t wg_font_offer;
extern const wg_font_t wg_font_msg;
extern const wg_font_t wg_font_msg_s;

#endif
